version: "3.9"  # optional since v1.27.0
services:
  web_api:
    build: .
    container_name: utilisateur
    ports:
      - "5000:80"
  sql:
    image: "mcr.microsoft.com/mssql/server:2022-latest"
    container_name: sqlserver 
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433" 
    environment:
      - ACCEPT_EULA=y
      - SA_PASSWORD=Fares5683@